#!/bin/bash
ffmpeg -framerate 30 -pattern_type glob -i "out_frames/*.png" -c:v libx264 -pix_fmt yuv420p temp.mp4
ffmpeg -i temp.mp4 -i audio.aac -map 0 -map 1:a -c:v copy -shortest out.mkv
rm temp.mp4
